EXE = debug
SFML_INCLUDE = C:/SFML-2.0/include
SFML_LIB = C:/SFML-2.0/lib

all: p.o a.o b.o d.o e.o f.o g.o h.o i.o j.o k.o l.o m.o n.o o.o r.o s.o t.o u.o v.o w.o x.o y.o z.o aa.o ab.o ac.o ad.o
	g++ -std=c++0x -static-libgcc -static-libstdc++ p.o a.o b.o d.o e.o f.o g.o h.o i.o j.o k.o l.o m.o n.o o.o r.o s.o t.o u.o v.o w.o x.o y.o z.o aa.o ab.o ac.o ad.o -o $(EXE) -L$(SFML_LIB) -L./lib -lsfml-network-d -lsfml-audio-d -lsfml-graphics-d -lsfml-window-d -lsfml-system-d -ltinylib

a.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c bond.cpp -o a.o

b.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c collision.cpp -o b.o

d.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c controlboard.cpp -o d.o

e.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c effects.cpp -o e.o

f.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c entity.cpp -o f.o

g.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c field.cpp -o g.o

h.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c floor.cpp -o h.o

i.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c gas.cpp -o i.o

j.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c gui.cpp -o j.o

k.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c interface.cpp -o k.o

l.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c item.cpp -o l.o

m.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c items.cpp -o m.o

n.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c machine.cpp -o n.o

o.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c machines.cpp -o o.o

p.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c main.cpp -o p.o

r.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c person.cpp -o r.o

s.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c player.cpp -o s.o

t.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c poster.cpp -o t.o

u.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c projectile.cpp -o u.o

v.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c prop.cpp -o v.o

w.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c rope.cpp -o w.o

x.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c scrap.cpp -o x.o

y.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c server.cpp -o y.o

z.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c session.cpp -o z.o

aa.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c talk.cpp -o aa.o

ab.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c terminal.cpp -o ab.o

ac.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c util.cpp -o ac.o

ad.o:
	g++ -static-libgcc -static-libstdc++ -I$(SFML_INCLUDE) -std=c++0x -c world.cpp -o ad.o


